### ISSUE TITLE
Make `Next` cloneable?

### ISSUE THREAD

**Issue by tirr-c** [rustasync/surf#32]
Sometimes middleware needs to make requests multiple times e.g. retry middleware. However, `Next::run` consumes self, so we can make only one actual request per call.

`Next` has immutable references only, so it's possible to make it derive `Clone`/`Copy`. Would it be okay to make it cloneable/copyable?

**Comment by fairingrey** [comment]
I think so, that type of behavior would definitely be warranted. Want to open a PR for it?

**Comment by yoshuawuyts** [comment]
@tirr-c this sounds very reasonable! If you have time a PR would indeed be great! :D

**Comment by tirr-c** [comment]
@fairingrey @yoshuawuyts Opened a PR!
