### ISSUE TITLE
Cannot convert Exception to failure::Error

### ISSUE THREAD

**Issue by vorot93** [rustasync/surf#45]
```
async fn main() -> failure::Fallible<()> {
    surf::Client::new()
        .get("https://google.com")
        .recv_json::<()>()
        .await?;

    Ok(())
}
```

yields

```
the size for values of type `dyn std::error::Error + std::marker::Send + std::marker::Sync` cannot be known at compilation time
```

**Comment by CryZe** [comment]
yeah Exception is just Box<dyn Error> which doesn't implement Error.

**Comment by Nemo157** [comment]
This is a `failure` issue: https://github.com/rust-lang-nursery/failure/issues/158, you have to use [`Error::from_boxed_compat`](https://docs.rs/failure/0.1.5/failure/struct.Error.html#method.from_boxed_compat)

**Comment by yoshuawuyts** [comment]
This seems to be an issue with `failure`, and probably resolved (:
