### ISSUE TITLE
How can I get the status code when using Request?

### ISSUE THREAD

**Issue by CarlosLanderas** [rustasync/surf#47]
Hello folks!
I have a function that looks like this:

 ```rust
    pub async fn get<T: DeserializeOwned>(&self, request_builder: &RequestBuilder) -> Vec<T> {
        let request = request_builder.build();
        let url = request.url().clone().into_string();
        let response_str = request.recv_string().await.unwrap();

        serde_json::from_str::<Vec<T>>(&response_str).unwrap()
    }
```

I've been looking around all the surf api surface, and swapping trying different methods like recv_string, or recv_json but if I do not use surf::Client.get I can't receive a Response object to check the Status Code and retrieve the body from there.

I need to use Request because I am using a RequestBuilder, and the idea is doing something like request.send and receive a Result with the response/error. Is this possible?

Thanks!

**Comment by Drevoed** [comment]
You should await on the request that you built. `Request`s implement `Future<Output = Result<Response, Exception>>`, which allow them to be polled(awaited) till completion, see example below:

```rust
#[runtime::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    let cli = Client::new();
    let req = cli.get("http://httpstat.us/502");
    let resp = req.await?;
    println!("status is {}", resp.status().as_u16());
    Ok(())
}
```

**Comment by CarlosLanderas** [comment]
I tried to do request.await because looking the source code I saw Request implements Future but I was not able to do it. I'll try again. Thank you very much!
